tunnel: __CF_TUNNEL_ID__
credentials-file: /etc/cloudflared/__CF_CREDENTIALS_FILE__

ingress:
  - hostname: __PREFECT_HOSTNAME__
    service: http://prefect-server:__PREFECT_PORT__
  - service: http_status:404
